name: check terraform code
on: 
  pull_request:
    branches:
      - "**"

jobs:
  check:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: aws_instance/create
    steps:
    - uses: actions/checkout@v4
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3

    - name: Terraform Init
      run: terraform init
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    - name: Terraform Format
      run: terraform fmt -check

    - name: Terraform Validate
      run: terraform validate

    - name: Plan Output
      id: plan_output
      run: |
        terraform plan -no-color >> plan.txt
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    - name: Plan Json
      run: |
        ls
        terraform show -json plan.txt >> plan.json
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - uses: actions/github-script@v6
      with: 
        github-token: ${{ secrets.COMMENT_PAT }}
        script: |
          const process = require('process')
          process.chdir('./aws_instance/create')
          console.log(process.cwd())
          const fs = require('fs')
          const fileContents = fs.readFileSync('./plan.txt').toString()
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: fileContents
          })
