name: check terraform code
on: 
  pull_request: 
   branches:
     - "**"

permissions: 
   pull-requests: write 

jobs:
  check:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: aws_instance/create
    steps:
    - uses: actions/checkout@v4
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3

    - name: Terraform Init
      run: terraform init
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    - name: Terraform Format
      run: terraform fmt -check

    - name: Terraform Validate
      run: terraform validate

    - name: Terraform Plan
      id: Terraform_Plan
      run: terraform plan -no-color
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    
    # - uses: thollander/actions-comment-pull-request@v2
    #   with: 
    #     message: |
    #       Terraform plan output:
    #       ```
    #       ${{ steps.Terraform_Plan.outputs.stdout }}
    #       ```
    - uses: actions/github-script@v6
      with: 
        script: |
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: ${{ steps.Terraform_Plan.outputs.stdout }}
          })